name: habitfit_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  #image picker
  image_picker: ^1.0.4

  # ✅ Flutter UI essentials
  cupertino_icons: ^1.0.8

  #notification_permissions:
  flutter_local_notifications: ^16.3.2




  # ✅ Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  google_sign_in: ^6.1.4

  # ✅ Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # ✅ Date and Time Formatting
  intl: ^0.18.1
  timezone: ^0.9.2

  # ✅ Progress Indicators
  percent_indicator: ^4.2.2

  # ✅ Real-time Location Tracking
  geolocator: ^13.0.4
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # ✅ Code Generation for Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/lose_weight_bmi_templates_all.json
    - assets/Build_muscle.json
    - assets/fix_sleep_template.json
    - assets/img/profile_placeholder.png
